apiVersion: v1
kind: ReplicationController
metadata:
    name: onem2m-1
    namespace: kube-system
spec:
    replicas: 1
    selector:
      app: onem2m-1
    template:
      metadata:
        name: onem2m-1
        labels:
          app: onem2m-1
      spec:
        containers:
        - name: onem2m-1
          image: huanphan/onem2m:2.0
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: onem2m-config
            mountPath: /usr/src/ipe_config/config.cfg
            subPath: config.cfg
          - name: onem2m-items
            mountPath: /usr/src/ipe_config/items.cfg
            subPath: items.cfg
        volumes:
        - name: onem2m-config
          configMap:
            name: onem2m-config-1
            items:
            - key: config.1.cfg
              path: config.cfg
        - name: onem2m-items
          configMap:
            name: onem2m-items-1
            items:
            - key: items.1.cfg
              path: items.cfg
        restartPolicy: Always
#        nodeSelector:
#          fog-node: worker_1